
# For more info on TOML syntax, please refer to:
# https://toml.io/en/v1.0.0

[d1]
a = 10 # This is d1.a
b = 11
c = 12
d = 10

[d2]
a = 17
b = 18
c = 19
d = 24

# The first value corresponds to single-level
# The second value corresponds to two-level

[d3]
a = [10, 10]
b = [20, 11]
c = [30, 12]
d = [40, 10]
e = [19, 19]
f = [29, 29]
g = [39, 30]
h = [49, 31]

[d4]
a = [24, 24]
b = [34, 25]
c = [44, 26]
d = [54, 54]
e = [26, 26]
f = [43, 43]
g = [53, 44]
h = [63, 45]

[d5]
a = [20, 20]
b = [30, 30]
c = [40, 31]
d = [50, 32]

[d6]
a = [27, 27]
b = [44, 44]
c = [54, 45]
d = [64, 46]
